#person:
#  name: dkt_${random.value}
#  age: ${random.int}
#  student: true
#  birth: 1999/03/03 23:12:59
#  #  maps:
#  #    book: 西游记
#  #    phone: oneplus
#  #  lists:
#  #    - test
#  #    - list集合
#  dog:
#    nickname: 小花狗_${person.name}
#    age: 3
#    parentsName: 小白狗和小棕狗_${dd.name:你爸爸}
#    children:
#      - 老大
#      - 老二
#      - 老三
#  maps: {book: 西游记, phone: oneplus}
#  lists: [list01, list02]
#
#server:
#  port: 8081
#
#dog:
#  nickname: 小黄
#  age: 1
#  parents-name: 小黑狗和小花狗
#  children:
#    - 老六
#    - 老九




---
spring:
  profiles:
    active: prod
---
server:
  port: 8088
spring:
  profiles: dev
---
server:
  port: 8090
spring:
  profiles: prod